//
// Created by h2279 on 2018/04/07.
//

#ifndef SHORTESTPATHALGORITHMWITHHEAPS_BASE_H
#define SHORTESTPATHALGORITHMWITHHEAPS_BASE_H

#define INFINITY 10000005
#define MAX 1005
typedef int Type;

#endif //SHORTESTPATHALGORITHMWITHHEAPS_BASE_H
